import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Head from "next/head";
import Image from "next/image";
import { FormEvent, useMemo, useState } from "react";
import {
  FaChevronLeft,
  FaChevronRight,
  FaEnvelope,
  FaGem,
  FaHouse,
  FaLocationDot,
  FaMagnifyingGlass,
  FaPhone,
  FaShieldHalved,
  FaScrewdriverWrench,
  FaUser,
} from "react-icons/fa6";

type Store = {
  name: string;
  image: string;
  state: string;
  district: string;
  address: string;
  contact: string;
  phone: string;
  email: string;
  type: "Authorized Dealer" | "Experience Centre";
  products: ("Doors" | "Windows")[];
};

const stores: Store[] = [
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Sri Sai Enterprises",
    image: "/images/store/store1.jpg",
    state: "Maharashtra",
    district: "Pune",
    address: "Shop No. 12, Sunshine Place, FC Road, Shivajinagar, Pune - 411005",
    contact: "Mr. Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@srisaiinteriors.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Modern Home Solutions",
    image: "/images/store/store2.jpg",
    state: "Karnataka",
    district: "Bengaluru",
    address: "#45, 2nd Floor, 100ft Ring Road, BTM Layout, Bengaluru - 560076",
    contact: "Ms. Pooja Iyer",
    phone: "+91 99887 66554",
    email: "pooja.iyer@modernhomes.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Galaxy Interiors",
    image: "/images/store/store3.jpg",
    state: "Tamil Nadu",
    district: "Chennai",
    address: "No. 28, Mount Road, Next to ICICI Bank, Chennai - 600002",
    contact: "Mr. Suresh Babu",
    phone: "+91 98450 77882",
    email: "galaxyinteriors@tata.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
  {
    name: "Shree Ram Traders",
    image: "/images/store/store4.jpg",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "Shop No. 8, Sardar Patel Market, Law Garden, Ahmedabad - 380006",
    contact: "Mr. Amit Patel",
    phone: "+91 98240 11223",
    email: "amit.patel@shreeramtraders.in",
    type: "Authorized Dealer",
    products: ["Doors", "Windows"],
  },
  {
    name: "Capital Door Gallery",
    image: "/images/store/store1.jpg",
    state: "Delhi",
    district: "New Delhi",
    address: "Ground Floor, Green Park Main Market, New Delhi - 110016",
    contact: "Ms. Nisha Verma",
    phone: "+91 98100 22664",
    email: "hello@capitaldoors.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Westside Windows",
    image: "/images/store/store2.jpg",
    state: "Maharashtra",
    district: "Mumbai",
    address: "Unit 4, Link Square Mall, Bandra West, Mumbai - 400050",
    contact: "Mr. Karan Mehta",
    phone: "+91 98201 45210",
    email: "sales@westsidewindows.in",
    type: "Authorized Dealer",
    products: ["Windows"],
  },
  {
    name: "Greenline Home Studio",
    image: "/images/store/store3.jpg",
    state: "Telangana",
    district: "Hyderabad",
    address: "Plot 18, Jubilee Hills Road No. 36, Hyderabad - 500033",
    contact: "Ms. Ananya Rao",
    phone: "+91 98490 55321",
    email: "studio@greenlinehome.in",
    type: "Experience Centre",
    products: ["Doors", "Windows"],
  },
  {
    name: "Coastal Door House",
    image: "/images/store/store4.jpg",
    state: "Kerala",
    district: "Kochi",
    address: "39 MG Road, Ernakulam South, Kochi - 682016",
    contact: "Mr. Joseph Mathew",
    phone: "+91 98470 14567",
    email: "contact@coastaldoorhouse.in",
    type: "Authorized Dealer",
    products: ["Doors"],
  },
];

const PAGE_SIZE = 50;

function StoreCard({ store }: { store: Store }) {
  return (
    <article className="store-locator__card">
      <div className="store-locator__showcase">
        <div className="store-locator__store-image">
          <Image src={store.image} alt={`${store.name} showroom`} fill sizes="(max-width: 680px) 100vw, (max-width: 1100px) 42vw, 280px" />
        </div>
        <div className="store-locator__brand-panel">
          <strong>Premium Doors &amp; Windows for a better tomorrow</strong>
          <div className="store-locator__benefits" aria-label="Tata Pravesh benefits">
            <span><FaShieldHalved aria-hidden="true" />Trusted<br />Quality</span>
            <span><FaGem aria-hidden="true" />Premium<br />Designs</span>
            <span><FaScrewdriverWrench aria-hidden="true" />Professional<br />Installation</span>
          </div>
        </div>
      </div>

      <div className="store-locator__details">
        <div className="store-locator__card-heading">
          <h2>{store.name}</h2>
          <p>{store.type}</p>
        </div>
        <div className="store-locator__location-row">
          <FaLocationDot aria-hidden="true" />
          <span><small>State</small>{store.state}</span>
          <span><small>District</small>{store.district}</span>
        </div>
        <div className="store-locator__detail-row">
          <span className="store-locator__detail-icon"><FaHouse aria-hidden="true" /></span>
          <span><small>Address</small>{store.address}</span>
        </div>
        <div className="store-locator__detail-row">
          <span className="store-locator__detail-icon"><FaUser aria-hidden="true" /></span>
          <span><small>Contact Person</small>{store.contact}</span>
        </div>
        <a className="store-locator__detail-row" href={`tel:${store.phone.replaceAll(" ", "")}`}>
          <span className="store-locator__detail-icon"><FaPhone aria-hidden="true" /></span>
          <span><small>Mobile No</small>{store.phone}</span>
        </a>
        <a className="store-locator__detail-row" href={`mailto:${store.email}`}>
          <span className="store-locator__detail-icon"><FaEnvelope aria-hidden="true" /></span>
          <span><small>Email Id</small>{store.email}</span>
        </a>
      </div>
    </article>
  );
}

export default function StoreLocatorPage() {
  const [query, setQuery] = useState("");
  const [submittedQuery, setSubmittedQuery] = useState("");
  const [storeType, setStoreType] = useState("all");
  const [product, setProduct] = useState("all");
  const [page, setPage] = useState(1);

  const filteredStores = useMemo(() => {
    const normalizedQuery = submittedQuery.trim().toLowerCase();

    return stores.filter((store) => {
      const matchesQuery = !normalizedQuery || [
        store.name,
        store.state,
        store.district,
        store.address,
      ].some((value) => value.toLowerCase().includes(normalizedQuery));
      const matchesType = storeType === "all" || store.type === storeType;
      const matchesProduct = product === "all" || store.products.some((availableProduct) => availableProduct === product);
      return matchesQuery && matchesType && matchesProduct;
    });
  }, [product, storeType, submittedQuery]);

  const pageCount = Math.max(1, Math.ceil(filteredStores.length / PAGE_SIZE));
  const visibleStores = filteredStores.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  const handleSearch = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setSubmittedQuery(query);
    setPage(1);
  };

  const updateFilter = (filter: "type" | "product", value: string) => {
    if (filter === "type") setStoreType(value);
    else setProduct(value);
    setPage(1);
  };

  const resetSearch = () => {
    setQuery("");
    setSubmittedQuery("");
    setStoreType("all");
    setProduct("all");
    setPage(1);
  };

  return (
    <>
      <Head>
        <title>Find a Store | Tata Pravesh</title>
        <meta name="description" content="Find an authorized Tata Pravesh dealer or experience centre near you." />
      </Head>
      <Header />
      <main className="store-locator">
        <section className="store-locator__hero" aria-labelledby="store-locator-title">
          <div className="store-locator__container store-locator__hero-inner">
            <p>Find a store</p>
            <h1 id="store-locator-title">Our Stores</h1>
            <span>Visit our authorized dealers and experience<br className="store-locator__desktop-break" /> Tata Pravesh doors and windows in person.</span>
          </div>
        </section>

        <div className="store-locator__main">
          <div className="store-locator__container">
            <form className="store-locator__search" onSubmit={handleSearch}>
              <label className="store-locator__search-location">
                <FaLocationDot aria-hidden="true" />
                <span>
                  
                  <span className="store-locator__input-wrap">
                    <input
                      type="search"
                      value={query}
                      onChange={(event) => setQuery(event.target.value)}
                      placeholder="Enter city, area or pincode"
                      aria-label="Search city, area or pincode"
                    />
                    <FaMagnifyingGlass aria-hidden="true" />
                  </span>
                </span>
              </label>
              
              
              <button className="store-locator__search-button" type="submit">
                <FaMagnifyingGlass aria-hidden="true" />Search Stores
              </button>
            </form>

            {visibleStores.length > 0 ? (
              <div className="store-locator__results" aria-live="polite">
                {visibleStores.map((store) => <StoreCard key={store.name} store={store} />)}
              </div>
            ) : (
              <div className="store-locator__empty" role="status">
                <FaLocationDot aria-hidden="true" />
                <h2>No stores found nearby</h2>
                <p>Try another city, area, or pincode, or reset the filters to see all stores.</p>
                <button type="button" onClick={resetSearch}>Show all stores</button>
              </div>
            )}

            {filteredStores.length > PAGE_SIZE && (
              <nav className="store-locator__pagination" aria-label="Store pages">
                <button type="button" aria-label="Previous page" disabled={page === 1} onClick={() => setPage((current) => current - 1)}>
                  <FaChevronLeft aria-hidden="true" />
                </button>
                {Array.from({ length: pageCount }, (_, index) => index + 1).map((pageNumber) => (
                  <button
                    type="button"
                    key={pageNumber}
                    aria-current={page === pageNumber ? "page" : undefined}
                    className={page === pageNumber ? "store-locator__page store-locator__page--active" : "store-locator__page"}
                    onClick={() => setPage(pageNumber)}
                  >
                    {pageNumber}
                  </button>
                ))}
                <button type="button" aria-label="Next page" disabled={page === pageCount} onClick={() => setPage((current) => current + 1)}>
                  <FaChevronRight aria-hidden="true" />
                </button>
              </nav>
            )}

            <section className="store-locator__contact" aria-label="Help finding a store">
              <span className="store-locator__contact-icon"><FaLocationDot aria-hidden="true" /></span>
              <div>
                <h2>Can’t find a store near you?</h2>
                <p>Get in touch with our team and we will help you find the nearest dealer.</p>
              </div>
              <a href="mailto:enquiry@tatapravesh.com?subject=Help%20finding%20a%20Tata%20Pravesh%20store">
                <FaEnvelope aria-hidden="true" />Contact Us
              </a>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}